# Generated by Django 4.0.2 on 2022-02-08 05:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.TextField()),
                ('error', models.TextField()),
                ('error_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.CharField(max_length=50)),
                ('transcript', models.TextField()),
                ('video_type', models.CharField(blank=True, max_length=200, null=True)),
                ('total_words', models.IntegerField(default=0)),
                ('average_confidence', models.DecimalField(blank=True, decimal_places=5, max_digits=30, null=True)),
                ('speak_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hurriness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('end_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('content', models.CharField(blank=True, max_length=30, null=True)),
                ('pron', models.CharField(blank=True, max_length=30, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('mean_time', models.DecimalField(blank=True, decimal_places=5, max_digits=30, null=True)),
                ('second', models.IntegerField(default=0)),
                ('video_type', models.CharField(blank=True, max_length=200, null=True)),
                ('transcript_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_details', to='aws_transcript.transcript')),
            ],
        ),
    ]
