# Generated by Django 4.0.2 on 2022-02-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_transcript', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='Candidate_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='Words_per_minute',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='questionID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='stutter_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='stutter_per_minute',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='is_stutter',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
