# Generated by Django 4.0.2 on 2022-02-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_transcript', '0003_questionanswer_transcript_video_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='cleaned_answer',
            field=models.TextField(blank=True, default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
