# Generated by Django 4.0.2 on 2022-02-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_transcript', '0004_questionanswer_cleaned_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringRelevance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField()),
                ('Candidate_id', models.CharField(blank=True, max_length=50, null=True)),
                ('questionID', models.CharField(blank=True, max_length=50, null=True)),
                ('video_type_id', models.IntegerField(blank=True, default=0, null=True)),
                ('video_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HiringVideoIdToVideoTypeMaping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type_id', models.IntegerField(blank=True, default=0, null=True)),
                ('video_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ErrorVideo',
            new_name='HiringErrorVideo',
        ),
        migrations.RenameModel(
            old_name='QuestionAnswer',
            new_name='HiringQuestionAnswer',
        ),
        migrations.RenameModel(
            old_name='Transcript',
            new_name='HiringTranscript',
        ),
        migrations.RenameModel(
            old_name='Word',
            new_name='HiringWord',
        ),
    ]
