# Generated by Django 4.0.2 on 2022-02-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_transcript', '0005_hiringrelevance_hiringvideoidtovideotypemaping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringrelevance',
            name='cleaned_transcript',
            field=models.TextField(blank=True, default='NA', null=True),
        ),
    ]
